name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greetings
        run: | 
            echo " Hello World!-1"
            echo " Hello World!-2"
      - name: Print Goodvyee
        run: echo "Done - bye!"
